### ISSUE TITLE
[bug] SfMTransform ignored by Nodes

### ISSUE THREAD

**Issue by datavizzard** [alicevision/Meshroom#1994]
**Describe the bug**
Insert SfMTransform is ignored by Meshing and following Nodes

**To Reproduce**
Insert SfMTransform between SFM and PrepareDenseScene, change Transformation Method to manual and modify the Orientation.

**Expected behavior**
Turn the sfmdata and keep orientation

**Screenshots**
![SfMTransform](https://user-images.githubusercontent.com/7428102/233804232-ccc87066-d9df-4652-82e2-f5f5a040d4d0.png)

**Desktop (please complete the following and other pertinent information):**
 - OS: Win10 21H2
 - Meshroom version: 2023.1.0

**Additional context**
![sfmpipeline](https://user-images.githubusercontent.com/7428102/233804425-191d0e2b-40cc-42c8-91ff-ed703ff53d72.png)

I tried to follow Glebs Tutorial at marker -> https://www.youtube.com/watch?v=j3lhPKF8qjU&t=919s

**Comment by MitchWoodin** [comment]
I'm getting the same result. It seems as though the sfmTransform node doesn't transfer it's attribute to further nodes?

**Comment by geoffhayford** [comment]
+1

**Comment by MitchWoodin** [comment]
I've also followed the steps outlined here:
https://github.com/alicevision/meshroom/wiki/Model-orientation

Both node setups produce the same outcome. I've also attempted to bypass the DepthMap nodes again the outcome is the same

**Comment by natowi** [comment]
You could try duplicating the SfMTransform node and try to merge them together with SfMAllignment

**Comment by avclubvids** [comment]
+1 to this bug, having the same result:
![SFMTransformBug](https://github.com/alicevision/Meshroom/assets/9397841/bf5141c0-2378-4e46-8861-1b83d4f572c7)

**Comment by vertices2edge** [comment]
+1

**Comment by datavizzard** [comment]
Solved in Meshroom 2023.2.0 (2023/06/26)

**Comment by avclubvids** [comment]
I think this is still a bug in 2023.2.0. The point cloud is properly transformed but the mesh is not - the mesh is rotated correctly, but transformed inversely:

![SFM_uncorrected](https://github.com/alicevision/Meshroom/assets/9397841/a6fea5d0-8d8d-4fd2-8431-715bf6282340)
![pointcloud_correct](https://github.com/alicevision/Meshroom/assets/9397841/ebc28ff2-f03f-4f50-bb34-754fcf58923b)
![mesh_incorrect](https://github.com/alicevision/Meshroom/assets/9397841/521822f6-0ae9-4307-b045-1ec38b01bdd9)

**Comment by joschi1212** [comment]
I am having the same issue. Using Meshroom-2023.2.0 downloaded from the official website. 
The point cloud is transformed correctly but the reconstruction is only rotated correctly but the translation is wrong. 
![image](https://github.com/alicevision/Meshroom/assets/10533665/effb8882-cfea-40da-b7f0-47287d34e81c)
In the middle is the original point cloud, on the right is the transformed point cloud and on the left is the reconstructed mesh.

**Comment by xuzhuang1996** [comment]
this problem has solved?

**Comment by MWoodinGit** [comment]
This is definitely not solved for me. I'm using 2023.3.0 and no matter what order I place the nodes the final output completely ignores the sfmTransform node.

If this has been solved are we doing something wrong?
