### ISSUE TITLE
Export Camera with corresponding image?

### ISSUE THREAD

**Issue by luminati** [alicevision/meshroom#441]
I can't get camera positions out of the Meshroom. I tried prexisting nodes with no luck. all cameras have 0.0.0 location and 0.0.0 rotations. Could it be possible to add to export them using any of the standard format like fbx, collada etc.?

**Comment by fabiencastan** [comment]
The output of the `StructureFromMotion` node is already using a standard file format: [Alembic](http://www.alembic.io). This file format is supported in most of the 3D editors.

**Comment by luminati** [comment]
I use blender and it crashes with alembic. unity can't open it either unfortunately. I don't have Autodesk products as they are commercial. Does Alembic support images?

**Comment by natowi** [comment]
@luminati Did you try https://github.com/unity3d-jp/AlembicForUnity or [UnityImporter](https://docs.unity3d.com/Packages/com.unity.formats.alembic@0.1-preview/manual/index.html)?

**Comment by SBCV** [comment]
I think this bug has been fixed in Blender 2.81 and not 2.8 beta (see https://developer.blender.org/rB2741992f6608c0f76e1bc95ca5d6e05a63348c7f).

The nightly build (https://builder.blender.org/download/) worked for me, the official release 2.80 did not.

**Comment by luminati** [comment]
Sorry, I didn't respond earlier but I couldn't get it to work. I wanted to dig deeper into documentation but I didn't find anything that would help me in the given time. I downloaded the newest blender (2.81). however, I still get cameras all cameras with (0,0,0) location and (0,0,0) orientations vectors. I don't know how to get cameras in correct places and with correct orientations.

**Comment by SBCV** [comment]
That is very strange, the fix "T61935: load camera transforms from Alembic files written by Meshroom" (https://developer.blender.org/rB2741992f6608c0f76e1bc95ca5d6e05a63348c7f) should address exactly this issue. Your Blender version must include this fix. Did you download the nightly build?

**Comment by luminati** [comment]
Ok, so, just in case downloaded the same build again. Ran simple 6 photo project. Didn't use any ConvertSfm etc. nodes. just loaded straight up sfm.abc file and it worked. 👍 
Now, is it possible to load cameras with corresponding images into blender? ;)

**Comment by SBCV** [comment]
I don't think so, but I'm currently working on an Blender Addon that allows you to import different photogrammetry results into blender (https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer). Unfortunately, Meshroom is not yet supported, but I think I ll add support for Meshroom next week. At least for .json / .sfm files.

**Comment by luminati** [comment]
OMG, your addon is amazing and exactly what I was looking for! Can't wait for the mesh room support. Will it support. The cameras import with correct transforms and bundled with images just like in your wiki? 
![image](https://user-images.githubusercontent.com/2597600/62709527-d8fb8880-b9f5-11e9-8c49-f39165a1d54a.png)

**Comment by SBCV** [comment]
Yepp, that is the purpose of it ;)

**Comment by fabiencastan** [comment]
You can have a look at the ExportMaya node, which creates undistorted images in half-resolution as well as thumbnails. Then we have a [plugin in Maya](https://github.com/alicevision/MeshroomMaya) to load the ABC file (using the native ABC loader) and it just setups the image planes.
It is possible to do the same approach in Blender (without having to parse custom file formats).

**Comment by luminati** [comment]
That's fantastic! I will keep an eye for the new version. Please feel free to drop me a message, I will gladly test it if you're interested. Thanks:)

**Comment by SBCV** [comment]
@fabiencastan I'm afraid I did not completely understand your message. What is the "native ABC loader"? Can you link the file that loads the ABC file format?
@luminati I ll come back to you, once Meshroom is supported

**Comment by SBCV** [comment]
@luminati The addon (https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer) supports now Meshroom's JSON format. There is an example file in the repository. If you have any questions let me know. 

Bests
